config/routes.rb
Rails.application.routes.draw do
  resources :password_category

  resources :passwords

  resources :expense_category
  resources :expenses
  resources :category  
  resources :bookmarks

  devise_for :users

  root 'site#index'

	

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :user
	belongs_to :category

	# ensure that a user_id is present
	validates :user_id, presence: true

	# ensure that a user_id is present
	validates :category_id, presence: true
	
	# ensure that title is present and at least 10 chars long
	validates :title, length: { minimum: 10 }, presence: true
	
	# ensure the url is present, and respects the URL format for http/https
	validates :url, format: {with: Regexp.new(URI::regexp(%w(http https)))}, presence: true

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
	before_action :authenticate_user!
	before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    # @bookmarks = Bookmark.onlyUser(current_user.id)
    @bookmarks = current_user.bookmarks
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
    @category =  current_user.category.all
  end

  # GET /bookmarks/1/edit
  def edit
    @category =  current_user.category.all
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create

    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.user_id=current_user.id
    
    
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
			unless @bookmark = current_user.bookmarks.where(id: params[:id]).first
			 flash[:alert] = 'Bookmark not found.'
			 redirect_to root_url
		  end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, :id, :category_id)
    end

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
	<%= f.error_notification %>
	
	<div class="form-inputs">
		<%= f.collection_select :category_id, @category, :id, :title%>
		<%= f.input :title %>
		<%= f.input :url %>
	</div>

	<div class="form-actions">
		<%= f.button :submit %>
	</div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark, :class=>"button tiny" %> 
<%= link_to 'Back', bookmarks_path, :class=>"button tiny" %>

app/views/bookmarks/index.html.erb
<h1>Listing Bookmarks</h1>

<div width="100%" align='right'>
  <%= link_to 'Bookmark Categories', category_index_path, :class=>"button radius" %>
</div>


<table width="100%">
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td width="35%"><%= bookmark.title %></td>
        <td width="45%"><%= bookmark.url %></td>
        <td width="20%" align="center">
          <%= link_to 'Show', bookmark, :class=>"button tiny" %>
          <%= link_to 'Edit', edit_bookmark_path(bookmark), :class=>"button tiny" %>
          <%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"button tiny alert" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path, :class=>"button radius" %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path, :class=>"button tiny" %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bookmark.category_id %>
</p>

<p>
  <strong>Id:</strong>
  <%= @bookmark.id %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark), :class=>"button tiny" %> 
<%= link_to 'Back', bookmarks_path, :class=>"button tiny" %>