config/routes.rb
Rails.application.routes.draw do
  resources :password_category

  resources :passwords

  resources :expense_category
  resources :expenses
  resources :category  
  resources :bookmarks

  devise_for :users

  root 'site#index'

	

end

app/models/expense_category.rb
class ExpenseCategory < ActiveRecord::Base
	belongs_to :user
	has_many :expenses
end

app/controllers/expense_category_controller.rb
class ExpenseCategoryController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense_category, only: [:show, :edit, :update, :destroy]

  # GET /expense_category
  # GET /expense_category.json
  def index
    @expense_category = current_user.expense_category.all
  end

  # GET /expense_category/1
  # GET /expense_category/1.json
  def show
  end

  # GET /expense_category/new
  def new
    @expense_category = ExpenseCategory.new
  end

  # GET /expense_category/1/edit
  def edit
  end

  # POST /expense_category
  # POST /expense_category.json
  def create
    @expense_category = ExpenseCategory.new(expense_category_params)
    @expense_category.user_id=current_user.id

    respond_to do |format|
      if @expense_category.save
        format.html { redirect_to @expense_category, notice: 'Expense category was successfully created.' }
        format.json { render :show, status: :created, location: @expense_category }
      else
        format.html { render :new }
        format.json { render json: @expense_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expense_category/1
  # PATCH/PUT /expense_category/1.json
  def update
    respond_to do |format|
      if @expense_category.update(expense_category_params)
        format.html { redirect_to @expense_category, notice: 'Expense category was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense_category }
      else
        format.html { render :edit }
        format.json { render json: @expense_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expense_category/1
  # DELETE /expense_category/1.json
  def destroy
    @expense_category.destroy
    respond_to do |format|
      format.html { redirect_to expense_category_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense_category
      # @expense_category = ExpenseCategory.where(:id => params[:id], :user_id => current_user.id).first
      unless @expense_category = current_user.expense_category.where(id: params[:id]).first
        flash[:alert] = 'Expense not found.'
        redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_category_params
      params.require(:expense_category).permit(:title, :description)
    end
end

app/helpers/expense_categories_helper.rb
module ExpenseCategoriesHelper
end

app/views/expense_category/_form.html.erb
<%= simple_form_for(@expense_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/expense_category/edit.html.erb
<h1>Editing Expense Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense_category, :class=>"button tiny" %> 
<%= link_to 'Back', expense_category_index_path, :class=>"button tiny" %>

app/views/expense_category/index.html.erb
<h1>Listing Expense Category</h1>

<table width="100%">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @expense_category.each do |expense_category| %>
      <tr>
        <td width="20%"><%= expense_category.title %></td>
        <td width="60%"><%= expense_category.description %></td>
        <td width="20%" align="center">
          <%= link_to 'Show', expense_category, :class=>"button tiny"%>
          <%= link_to 'Edit', edit_expense_category_path(expense_category), :class=>"button tiny" %>
          <%= link_to 'Destroy', expense_category, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"button tiny alert" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense category', new_expense_category_path, :class => "button radius" %>

app/views/expense_category/new.html.erb
<h1>New expense_category</h1>

<%= render 'form' %>

<%= link_to 'Back', expense_category_index_path, :class=>"button tiny" %>

app/views/expense_category/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @expense_category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense_category.description %>
</p>

<%= link_to 'Edit', edit_expense_category_path(@expense_category), :class=>"button tiny" %> 
<%= link_to 'Back', expense_category_index_path, :class=>"button tiny" %>