config/routes.rb
Rails.application.routes.draw do
  resources :password_category

  resources :passwords

  resources :expense_category
  resources :expenses
  resources :category  
  resources :bookmarks

  devise_for :users

  root 'site#index'

	

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = current_user.expenses
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @category =  current_user.expense_category.all
  end

  # GET /expenses/1/edit
  def edit
    @category =  current_user.expense_category.all
  end

  # POST /expenses
  # POST /expenses.json
  def create

    @expense = Expense.new(expense_params)
    @expense.user_id=current_user.id

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      # @expense = Expense.find(params[:id])
      unless @expense = current_user.expenses.where(id: params[:id]).first
       flash[:alert] = 'Expense not found.'
       redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:description, :cost, :ExpenseCategory_id)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.collection_select :ExpenseCategory_id, @category, :id, :title, :selected => @expense.ExpenseCategory_id, :class=> "dropdown"%>
  	<!-- class="[tiny small medium large] [secondary alert success] [radius round] button dropdown" -->
    <%= f.input :description %>
    <%= f.input :cost %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense, :class=>"button tiny" %>
<%= link_to 'Back', expenses_path, :class => "button tiny" %>

app/views/expenses/index.html.erb
<h1>Listing Expenses</h1>

<div width="100%" align='right'>
  <%= link_to 'Expenses Categories', expense_category_index_path, :class=>"button radius" %>
</div>

<table width="100%">
  <thead>
    <tr>
      <th>Description</th>
      <th>Cost</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td width="70%"><%= expense.description %></td>
        <td width="10%"><%= expense.cost %></td>
        <td width="20%" align="center">
          <%= link_to 'Show', expense, :class=>"button tiny" %>
          <%= link_to 'Edit', edit_expense_path(expense), :class=>"button tiny" %>
          <%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"button tiny alert" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path, :class=>"button radius" %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path, :class=>"button tiny" %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @expense.cost %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense), :class=>"button tiny" %> 
<%= link_to 'Back', expenses_path, :class=>"button tiny" %>